### ISSUE TITLE
Game over when pressing to go back

### ISSUE THREAD

**Issue by ShutDownMan** [victorhugoturnes/snake#1]
I don't think it's a good thing to game over when the player tries to go back on itself, sometimes you press it accidentally and it becomes very frustrating.

Also, it's real lazy not implementing that check '-------------'

**Comment by ShutDownMan** [comment]
Apparently it's a feature.

**Comment by victorhugoturnes** [comment]
Fixed for commit 61405f8f669d84bc760ee348e4793dc206dbb2c8, should be up soon.
